import Foundation

// MARK: - Epic #53: Provider-neutral abstraction

/// An SDK-independent representation of one part of an AI prompt.
/// Before Epic #53 the protocol leaned directly on `GoogleGenerativeAI.ModelContent.Part`,
/// which tied the entire inference layer to Gemini. This value type decouples the
/// call sites from the SDK so OpenAI/Claude/Mistral clients can implement the same
/// protocol. Each provider client maps these parts to its own wire format
/// (see `AIModelFactory`).
public enum AIPromptPart {
    /// Plain text (the user question + injected context prefix).
    case text(String)
    /// Binary image data with its associated MIME type (e.g. `image/jpeg`).
    case imageData(Data, mimeType: String)
}

/// Provider-agnostic error thrown by the REST clients (OpenAI/Claude/Mistral).
/// `ChatViewModel`, `WorkoutInsightService` and `ChatErrorMessageMapper` map these
/// to the right fallback/UI handling, so the 503/429 waterfall and the auth-error
/// detection are no longer Gemini-SDK-specific.
///
/// Transport errors (offline, timeout, DNS) are deliberately **not** captured in
/// this type — we let those bubble up as `URLError` so the existing
/// `ChatErrorMessageMapper` URLError mapping handles them.
public enum AIProviderError: Error, Equatable {
    /// HTTP 429/503/529 — provider temporarily overloaded. Triggers the fallback waterfall.
    case overloaded
    /// HTTP 401/403 or an invalid/revoked key.
    case authenticationFailed
    /// The response was blocked by a safety filter.
    case contentBlocked
    /// Another non-2xx status code. `message` contains (a truncated) provider error
    /// body so the user/diagnostics see why (e.g. a deprecated model).
    case http(status: Int, message: String?)
    /// 2xx, but no usable text in the response body.
    case emptyResponse
    /// The response body couldn't be parsed into the expected JSON schema.
    case decodingFailed
}

extension AIProviderError {
    /// True if an error is a temporary overload and it makes sense to try the
    /// fallback model. Story 61.8: simplified — all four providers now throw
    /// `.overloaded` directly from their REST clients; the old Gemini-SDK
    /// string-matching fallback is no longer needed.
    public static func isOverload(_ error: Error) -> Bool {
        if let providerError = error as? AIProviderError {
            return providerError == .overloaded
        }
        return false
    }
}

/// A protocol that abstracts the required capabilities of a generative AI model.
/// This lets us replace the implementation with a mock for unit testing, and put a
/// dedicated client per provider (Gemini/OpenAI/Claude/Mistral) behind the same
/// contract.
public protocol GenerativeModelProtocol {
    /// Generates content based on the given, SDK-independent parts.
    ///
    /// - Parameter parts: An array of `AIPromptPart` (text and/or images).
    /// - Returns: A textual response generated by the AI model.
    func generateContent(_ parts: [AIPromptPart]) async throws -> String?
}

/// Marker protocol for a real provider client (not a test mock). `ChatViewModel`
/// uses this to apply the API-key gate (`hasAPIKey`) only to live clients —
/// injected mocks (`MockGenerativeModel`, `UITestMockGenerativeModel`)
/// deliberately don't conform, so tests don't trip over a missing key.
public protocol RealAIProviderClient {}
